name: bayut-cheker
on: push
jobs:
    deploy-nginx-to-server:
        name: deploy-nginx-to-server
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
          
            - name: print out example job
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                key: ${{ secrets.KEY }}
                username: ${{secrets.USERNAME}}
                passphrase: ${{secrets.PASSPHRASE}}
                port: 22
                command_timeout: 30m
                script: | 
                  echo "Nice Job!!!"
            
            - name: Build Nginx docker image
              run: |
                docker build -f nginxdockerfile -t bayut-docker:0.0.2 .
                
            - name: Save nginx docker image as tar
              run: |
                docker save bayut-docker:0.0.2 -o bayut-docker.tar
                chmod 644 bayut-docker.tar

            
            - name: Copy Nginx docker image to droplet
              uses: appleboy/scp-action@v0.1.7
              with:
                    host: ${{secrets.HOST}}
                    username: ${{secrets.USERNAME}}
                    passphrase: ${{secrets.PASSPHRASE}}
                    key: ${{secrets.KEY}}
                    source: bayut-docker.tar
                    target: ~/images


            - name: Load the nginx and app docker image to run
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{secrets.HOST}}
                username: ${{secrets.USERNAME}}
                passphrase: ${{secrets.PASSPHRASE }}
                key: ${{secrets.KEY}}
                script: |
                    docker load -i /root/images/bayut-docker.tar
                    docker rm -f bayut-docker
                    docker rm -f bayut-docker-app
           
    # deploy-app-to-server:
    #     needs: bayut-check
    #     name: deploy-app-to-server
    #     runs-on: ubuntu-latest

    #     steps:
    #     - name: Checkout Code
    #         uses: actions/checkout@v3

    #     - name: Build app docker image
    #         run: |
    #         docker build -f appdockerfile -t hh-docker-app:0.0.2 .
        
    #     - name: Save app docker image as tar
    #         run: |
    #         docker save hh-docker-app:0.0.2 -o hh-docker-app.tar
    #         chmod 644 hh-docker-app.tar
        
    #     - name: Copy app docker image to droplet
    #         uses: appleboy/scp-action@v0.1.7
    #         with:
    #         host: ${{secrets.HOST}}
    #         username: ${{secrets.USERNAME}}
    #         passphrase: ${{ secrets.PASSPHRASE }}
    #         key: ${{secrets.KEY}}
    #         source: hh-docker-app.tar
    #         target: ~/images

    #     - name: Load the app docker image on the server
    #         uses: appleboy/ssh-action@master
    #         with:
    #         host: ${{secrets.HOST}}
    #         username: ${{secrets.USERNAME}}
    #         passphrase: ${{ secrets.PASSPHRASE }}
    #         key: ${{secrets.KEY}}
    #         command_timeout: 20m
    #         script: |
    #             docker load -i /root/images/hh-docker-app.tar
        



