name: bayut-cheker
on: push
jobs:
    bayut-check:
        name: bayut checker
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
           
            - name: Build Nginx docker image
              run: |
                docker build -f nginxdockerfile -t bayut-docker:0.0.2 .
                
            - name: Save nginx docker image as tar
              run: |
                docker save bayut-docker:0.0.2 -o bayut-docker.tar
                chmod 644 bayut-docker.tar

            - name: Copy Nginx docker image to droplet
              uses: appleboy/scp-action@v0.1.7
              with:
                    host: ${{secrets.HOST}}
                    username: ${{secrets.USERNAME}}
                    passphrase: ${{secrets.PASSPHRASE}}
                    key: ${{secrets.KEY}}
                    source: bayut-docker.tar
                    target: ~/images
                    debug: true


            - name: Load the nginx and app docker image to run
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{secrets.HOST}}
                username: ${{secrets.USERNAME}}
                passphrase: ${{ secrets.PASSPHRASE }}
                key: ${{secrets.KEY}}
                script: |
                    docker load -i /root/images/bayut-docker.tar
                    docker rm -f bayut-docker
                    docker rm -f bayut-docker-app
           
                  



